import express from 'express';
import mongoose from 'mongoose';
import cors from 'cors';
import dotenv from 'dotenv';
import dns from 'dns';
import fs from 'fs/promises';
import path from 'path';
import nodemailer from 'nodemailer';

const BACKUP_FILE = path.join(process.cwd(), 'messages.json');

// Email Notification Helper
async function sendEmailNotification(messageData) {
  const { name, email, message } = messageData;
  const smtpUser = process.env.SMTP_USER;
  const smtpPass = process.env.SMTP_PASS;
  const smtpReceiver = process.env.SMTP_RECEIVER || 'tonifavouretim@gmail.com';

  if (!smtpUser || !smtpPass) {
    console.warn('Email notification skipped: SMTP_USER or SMTP_PASS environment variables are not configured.');
    return;
  }

  // Create transporter using Gmail service
  const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
      user: smtpUser,
      pass: smtpPass
    }
  });

  const mailOptions = {
    from: `"${name} via Portfolio" <${smtpUser}>`,
    to: smtpReceiver,
    replyTo: email,
    subject: `New Portfolio Message from ${name}`,
    text: `You received a new message from your portfolio contact form:

Name: ${name}
Email: ${email}
Date: ${new Date().toLocaleString()}

Message:
------------------------------------------
${message}
------------------------------------------`,
    html: `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e2e8f0; border-radius: 12px; background-color: #ffffff;">
        <h2 style="color: #2563eb; margin-top: 0;">New Contact Form Message</h2>
        <p style="font-size: 16px; color: #4a5568;">You received a new message from your portfolio website.</p>
        
        <table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
          <tr>
            <td style="padding: 8px 0; font-weight: bold; color: #4a5568; border-bottom: 1px solid #edf2f7; width: 100px;">Name:</td>
            <td style="padding: 8px 0; color: #2d3748; border-bottom: 1px solid #edf2f7;">${name}</td>
          </tr>
          <tr>
            <td style="padding: 8px 0; font-weight: bold; color: #4a5568; border-bottom: 1px solid #edf2f7;">Email:</td>
            <td style="padding: 8px 0; border-bottom: 1px solid #edf2f7;"><a href="mailto:${email}" style="color: #2563eb; text-decoration: none;">${email}</a></td>
          </tr>
          <tr>
            <td style="padding: 8px 0; font-weight: bold; color: #4a5568; border-bottom: 1px solid #edf2f7;">Date:</td>
            <td style="padding: 8px 0; color: #2d3748; border-bottom: 1px solid #edf2f7;">${new Date().toLocaleString()}</td>
          </tr>
        </table>
        
        <div style="margin-top: 20px;">
          <h3 style="color: #4a5568; margin-bottom: 8px;">Message:</h3>
          <div style="padding: 16px; background-color: #f7fafc; border-left: 4px solid #2563eb; border-radius: 4px; color: #2d3748; line-height: 1.6; white-space: pre-wrap;">${message}</div>
        </div>
        
        <hr style="border: 0; border-top: 1px solid #edf2f7; margin: 30px 0;" />
        <p style="font-size: 12px; color: #a0aec0; text-align: center; margin-bottom: 0;">This email was automatically generated by your Portfolio server.</p>
      </div>
    `
  };

  try {
    await transporter.sendMail(mailOptions);
    console.log(`Notification email successfully sent to ${smtpReceiver}`);
  } catch (error) {
    console.error('Failed to send email notification:', error.message);
  }
}

// Set DNS servers to resolve MongoDB Atlas SRV records correctly on some Windows configurations
dns.setServers(['8.8.8.8', '1.1.1.1']);

dotenv.config();

const app = express();
const PORT = process.env.PORT || 5000;

// Middleware
app.use(cors());
app.use(express.json());

// Disable buffering globally
mongoose.set('bufferCommands', false);

// MongoDB Connection
const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/portfolio';
mongoose.connect(MONGODB_URI, {
  serverSelectionTimeoutMS: 2500, // Quick fail if database is offline (2.5s instead of 30s)
  bufferCommands: false // Disable buffering for all models on this connection
})
  .then(() => console.log('Connected to MongoDB successfully'))
  .catch(err => console.error('MongoDB connection error:', err));

mongoose.connection.on('error', err => {
  console.error('MongoDB connection error event:', err.message);
});

// Schema and Model
const contactSchema = new mongoose.Schema({
  name: {
    type: String,
    required: [true, 'Name is required'],
    trim: true
  },
  email: {
    type: String,
    required: [true, 'Email is required'],
    trim: true,
    match: [/\S+@\S+\.\S+/, 'Please use a valid email address']
  },
  message: {
    type: String,
    required: [true, 'Message is required'],
    trim: true,
    minlength: [10, 'Message must be at least 10 characters long']
  },
  createdAt: {
    type: Date,
    default: Date.now
  }
}, {
  bufferCommands: false // Disable buffering so Mongoose queries fail immediately if DB is offline
});

const ContactMessage = mongoose.model('ContactMessage', contactSchema);

// API Route
app.post('/api/contact', async (req, res) => {
  const { name, email, message } = req.body;

  // Validate incoming request body first
  if (!name || !email || !message) {
    return res.status(400).json({
      success: false,
      message: 'Name, email, and message are required'
    });
  }

  const messageData = {
    name,
    email,
    message,
    createdAt: new Date()
  };

  // Trigger email notification in background (non-blocking)
  sendEmailNotification(messageData).catch(err => {
    console.error('Background email notification failed:', err);
  });

  // Check if MongoDB is connected (readyState 1)
  if (mongoose.connection.readyState !== 1) {
    console.warn('Database connection is not active. Falling back to local storage.');
    try {
      let existingMessages = [];
      try {
        const fileContent = await fs.readFile(BACKUP_FILE, 'utf-8');
        existingMessages = JSON.parse(fileContent);
      } catch (readError) {
        // File doesn't exist yet or is empty/corrupt
      }

      existingMessages.push({ ...messageData, savedLocally: true });
      await fs.writeFile(BACKUP_FILE, JSON.stringify(existingMessages, null, 2), 'utf-8');

      return res.status(201).json({
        success: true,
        message: 'Message received and saved locally (offline mode)',
        data: messageData
      });
    } catch (fsError) {
      console.error('Failed to save message to local fallback:', fsError.message);
      return res.status(503).json({
        success: false,
        message: 'Database is offline and local fallback failed. Please try again later.'
      });
    }
  }

  try {
    const newMessage = new ContactMessage(messageData);
    const savedMessage = await newMessage.save();
    return res.status(201).json({
      success: true,
      message: 'Message saved successfully',
      data: savedMessage
    });
  } catch (err) {
    console.error('Failed to save message to database:', err.message);

    // If saving to DB fails, try the local fallback as well
    try {
      let existingMessages = [];
      try {
        const fileContent = await fs.readFile(BACKUP_FILE, 'utf-8');
        existingMessages = JSON.parse(fileContent);
      } catch (readError) {}

      existingMessages.push({ ...messageData, savedLocally: true });
      await fs.writeFile(BACKUP_FILE, JSON.stringify(existingMessages, null, 2), 'utf-8');

      return res.status(201).json({
        success: true,
        message: 'Message saved locally (database error fallback)',
        data: messageData
      });
    } catch (fsError) {
      return res.status(500).json({
        success: false,
        message: err.message || 'Failed to save message'
      });
    }
  }
});

// Start Server
app.listen(PORT, () => {
  console.log(`Server is running on port ${PORT}`); // Express server listener
});

