/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#d8dadc",
        "surface-bright": "#f7f9fb",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#360f00",
        "surface-container-low": "#f2f4f6",
        "secondary": "#595e70",
        "primary-fixed-dim": "#b4c5ff",
        "tertiary": "#943700",
        "on-primary-container": "#eeefff",
        "inverse-primary": "#b4c5ff",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#ffb596",
        "surface-container": "#eceef0",
        "on-primary": "#ffffff",
        "secondary-fixed": "#dee1f7",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#434655",
        "outline-variant": "#c3c6d7",
        "on-primary-fixed": "#00174b",
        "on-secondary-fixed": "#161b2b",
        "on-secondary-container": "#5d6274",
        "error": "#ba1a1a",
        "primary-fixed": "#dbe1ff",
        "inverse-on-surface": "#eff1f3",
        "primary": "#004ac6",
        "surface-tint": "#0053db",
        "secondary-fixed-dim": "#c2c6db",
        "surface-variant": "#e0e3e5",
        "tertiary-fixed": "#ffdbcd",
        "background": "#f7f9fb",
        "surface-container-high": "#e6e8ea",
        "on-surface": "#191c1e",
        "surface-container-highest": "#e0e3e5",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "on-tertiary-container": "#ffede6",
        "error-container": "#ffdad6",
        "secondary-container": "#dbdff4",
        "surface": "#f7f9fb",
        "primary-container": "#2563eb",
        "on-tertiary-fixed-variant": "#7d2d00",
        "on-primary-fixed-variant": "#003ea8",
        "inverse-surface": "#2d3133",
        "outline": "#737686",
        "on-background": "#191c1e",
        "on-secondary-fixed-variant": "#414658",
        "tertiary-container": "#bc4800"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "stack-md": "16px",
        "section-padding": "120px",
        "gutter": "24px",
        "stack-sm": "8px",
        "section-padding-mobile": "64px",
        "container-max": "1280px",
        "stack-lg": "24px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "display-xl": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "display-xl-mobile": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["30px", { lineHeight: "38px", fontWeight: "700" }],
        "display-xl": ["72px", { lineHeight: "80px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["20px", { lineHeight: "32px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "700" }],
        "display-xl-mobile": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.01em", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
